### ISSUE TITLE
2.0.0-rc.1 bug: cat hang on md5sum

### ISSUE THREAD

**Issue by Xuanwo** [qingstor/qsctl#236]
`qsctl cat qs://xxxx > xxxxx` hang

```
DEBU[2020-04-02T17:55:46+08:00] Started MD5SumFileTask {Offset: 0, Path: jdk-8u112-linux-x64.tar.gz, Size: 183212596, Storage: Storager qingstor {Name: xxxxxx, Location: pek3a, WorkDir: /}}
```

**Comment by Prnyself** [comment]
It was caught by md5sum task, which would read the file for md5 count, and that caused another file read. So we decide to remove md5sum for now, and will add it back after md5 check added.
