### ISSUE TITLE
Progress rate / progress bar support

### ISSUE THREAD

**Issue by jerryjedi** [qingstor/qsctl#324]
I use "qsctl cp" to upload a large file to qingstor on qingcloud.com，but "qsctl cp" doesn't display the progress rate, I don't know the status of the upload, just wait for the end. 

Please add the "progress rate" of qsctl command.

**Comment by Xuanwo** [comment]
We will implement this feature into `qsctl shell` in v2.3.0.

**Comment by Prnyself** [comment]
We've added support in `qsctl shell` in v2.3.0 (latest version). You can try `qsctl shell` and then just `cp` and progress bar is expected to show.
A lot of new interactive features were added in `qsctl shell`, such as command auto completion, history commands and so on, wish you have fun :).

**Comment by Xuanwo** [comment]
Closed for PR https://github.com/qingstor/qsctl/pull/331 merged.
