### ISSUE TITLE
met error when install qsctl

### ISSUE THREAD

**Issue by jerryjedi** [qingstor/qsctl#73]
ubuntu 16.04. 
First install, root user, pip 8.1.2, error message:
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6iS1nI/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0dESnP-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-6iS1nI/pycrypto/

upgrade pip to 19.1.1
Second installation, same server, root user, error message:
Running setup.py install for pycrypto ... error
    ERROR: Complete output from command /usr/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-oiuhcr/pycrypto/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-NfQ6_6/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/Crypto
    copying lib/Crypto/__init__.py -> build/lib.linux-x86_64-2.7/Crypto
    copying lib/Crypto/pct_warnings.py -> build/lib.linux-x86_64-2.7/Crypto
    creating build/lib.linux-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA224.py -> build/lib.linux-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA384.py -> build/lib.linux-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/MD5.py -> build/lib.linux-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/RIPEMD.py -> build/lib.linux-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/MD2.py -> build/lib.linux-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/__init__.py -> build/lib.linux-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/HMAC.py -> build/lib.linux-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA512.py -> build/lib.linux-x86_64-2.7/Crypto/Hash
.......

maybe the actual error was from "pip install pycrypto"

**Comment by Xuanwo** [comment]
pycrypto is too old, and we have already removed it from qignstor-sdk-python.

We will update qsctl to fix this problem.

**Comment by jerryjedi** [comment]
do you fix the problem?

**Comment by Xuanwo** [comment]
We are working on a go version of qsctl
